/*
 * TelstraAPIs.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 on 04/15/2016
 */
using System;

namespace TelstraAPIs.PCL
{
    public partial class Configuration
    {
        //The base Uri for API calls
        public static string BaseUri = "https://kloudapi.azure-api.net/telstra";

    }
}