/*
 * TelstraAPIs.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 on 04/15/2016
 */
using System;
using TelstraAPIs.PCL.Controllers;
using TelstraAPIs.PCL.Http.Client;

namespace TelstraAPIs.PCL
{
    public partial class TelstraAPIsClient
    {

        /// <summary>
        /// Singleton access to Client controller
        /// </summary>
        public APIController Client
        {
            get
            {
                return APIController.Instance;
            }
        }

        /// <summary>
        /// The shared http client to use for all API calls
        /// </summary>
        public IHttpClient SharedHttpClient
        {
            get
            {
                return BaseController.ClientInstance;
            }
            set
            {
                BaseController.ClientInstance = value;
            }        
        }
        
        /// <summary>
        /// Default constructor
        /// </summary>
        public TelstraAPIsClient() { }
    }
}